// Generated by ahp-codegen. DO NOT EDIT.
// Generated from AHP schema draft.
// The source schema is authoritative if this output conflicts with it.

export const SCHEMA_REVISION = "draft" as const;
export const PROTOCOL_VERSION = "draft" as const;

export type JsonPrimitive = null | boolean | number | string;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type AdditionalProperties = { [key: string]: JsonValue };
export type OpenString<Known extends string> = Known | (string & {});
export type UnknownVariant<Discriminator extends string> = AdditionalProperties & { [Key in Discriminator]: string };

export interface ParseDiagnostic {
  readonly path: string;
  readonly code: "invalid_type" | "missing_required" | "literal_mismatch" | "unknown_enum" | "unknown_variant" | "invalid_known_variant" | "no_union_match" | "ambiguous_union" | "invalid_json";
  readonly severity: "error" | "warning";
  readonly message: string;
}

export type ParseResult<T> =
  | { readonly ok: true; readonly value: T; readonly raw: JsonValue; readonly diagnostics: readonly ParseDiagnostic[] }
  | { readonly ok: false; readonly raw?: JsonValue; readonly diagnostics: readonly ParseDiagnostic[] };

type SchemaNode =
  | { kind: "any" | "never" | "null" | "boolean" | "integer" | "number" | "string" }
  | { kind: "literal"; value: JsonValue }
  | { kind: "enum"; values: JsonValue[]; open_strings: boolean }
  | { kind: "array"; items: SchemaNode }
  | { kind: "object"; properties: Array<{ wire_name: string; required: boolean; shape: SchemaNode }>; forbidden_property_sets: string[][]; additional: unknown }
  | { kind: "union"; mode: "anyOf" | "oneOf"; variants: SchemaNode[]; discriminator?: string }
  | { kind: "intersection"; variants: SchemaNode[] }
  | { kind: "ref"; name: string };

/** Source: schema/draft/registration.schema.json#/$defs/authentication */
export type Authentication = {
  "tokenEnv": string;
  "type": "bearer";
} & AdditionalProperties;

/** Source: schema/draft/registration.schema.json#/$defs/backend */
export type Backend = {
  "authentication"?: Authentication;
  "id": ReverseDnsName;
  "subscriptions": Array<InterceptSubscription | ObserveSubscription | UnknownVariant<"mode">>;
  "transport": StdioTransport | HttpTransport | UnknownVariant<"type">;
} & AdditionalProperties;

/** Source: schema/draft/capabilities.schema.json# */
export type Capabilities = {
  "effects": Array<"deny" | string>;
} & AdditionalProperties;

/** Source: schema/draft/deny-effect.schema.json# */
export type DenyEffect = {
  "code"?: string;
  "extensions"?: Extensions;
  "reason": string;
  "type": "deny";
} & AdditionalProperties;

/** Source: schema/draft/extensions.schema.json# */
export type Extensions = {
} & AdditionalProperties;

/** Source: schema/draft/registration.schema.json#/$defs/httpTransport */
export type HttpTransport = {
  "type": "http";
  "url": string;
} & AdditionalProperties;

/** Source: schema/draft/intercept-deny-response.schema.json# */
export type InterceptDenyResponse = JsonRpcSuccessResponse & {
  "result"?: {
    "effects": Array<DenyEffect>;
    "extensions"?: Extensions;
    "protocolVersion": ProtocolVersion;
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/intercept-no-effect-response.schema.json# */
export type InterceptNoEffectResponse = JsonRpcSuccessResponse & {
  "result"?: {
    "effects": Array<JsonValue>;
    "extensions"?: Extensions;
    "protocolVersion": ProtocolVersion;
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/intercept-request.schema.json# */
export type InterceptRequest = JsonRpcRequest & {
  "method"?: "hooks/intercept";
  "params"?: {
    "capabilities": Capabilities & {
      "effects"?: JsonValue;
    } & AdditionalProperties;
    "event": ToolBeforeEvent;
    "extensions"?: Extensions;
    "protocolVersion": ProtocolVersion;
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/registration.schema.json#/$defs/interceptSubscription */
export type InterceptSubscription = {
  "events": Array<"tool.before">;
  "failurePolicy": OpenString<"fail-open" | "fail-closed">;
  "includeNative"?: boolean;
  "mode": "intercept";
  "timeoutMs": number;
} & AdditionalProperties;

/** Source: schema/draft/common.schema.json#/$defs/errorResponse */
export type JsonRpcErrorResponse = {
  "error": {
    "code": number;
    "data"?: JsonValue;
    "message": string;
  } & AdditionalProperties;
  "id": JsonRpcResponseId;
  "jsonrpc": "2.0";
} & AdditionalProperties;

/** Source: schema/draft/common.schema.json#/$defs/jsonRpcId */
export type JsonRpcId = string | number;

/** Source: schema/draft/json-rpc-message.schema.json# */
export type JsonRpcMessage = JsonRpcRequest | JsonRpcNotification | JsonRpcSuccessResponse | JsonRpcErrorResponse;

/** Source: schema/draft/common.schema.json#/$defs/notification */
export type JsonRpcNotification = {
  "jsonrpc": "2.0";
  "method": string;
  "params": {
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/common.schema.json#/$defs/request */
export type JsonRpcRequest = {
  "id": JsonRpcId;
  "jsonrpc": "2.0";
  "method": string;
  "params": {
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/common.schema.json#/$defs/jsonRpcResponseId */
export type JsonRpcResponseId = JsonRpcId | null;

/** Source: schema/draft/common.schema.json#/$defs/successResponse */
export type JsonRpcSuccessResponse = {
  "id": JsonRpcResponseId;
  "jsonrpc": "2.0";
  "result": {
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/common.schema.json#/$defs/native */
export type NativeEvent = {
  "eventName": string;
  "payload": {
  } & AdditionalProperties;
  "provider": string;
} & AdditionalProperties;

/** Source: schema/draft/observe-notification.schema.json# */
export type ObserveNotification = JsonRpcNotification & {
  "method"?: "hooks/observe";
  "params"?: {
    "event": ToolBeforeEvent | ToolAfterEvent | ToolErrorEvent | SessionStartEvent | SessionEndEvent | UnknownVariant<"type">;
    "protocolVersion": ProtocolVersion;
  } & AdditionalProperties;
} & AdditionalProperties;

/** Source: schema/draft/registration.schema.json#/$defs/observeSubscription */
export type ObserveSubscription = {
  "events": Array<OpenString<"tool.before" | "tool.after" | "tool.error" | "session.start" | "session.end">>;
  "includeNative"?: boolean;
  "mode": "observe";
} & AdditionalProperties;

/** Source: schema/draft/common.schema.json#/$defs/protocolVersion */
export type ProtocolVersion = "draft";

/** Source: schema/draft/registration.schema.json# */
export type Registration = {
  "hooks": Array<Backend>;
  "protocolVersion": ProtocolVersion;
} & AdditionalProperties;

/** Source: schema/draft/registration.schema.json#/$defs/reverseDns */
export type ReverseDnsName = string;

/** Source: schema/draft/common.schema.json#/$defs/session */
export type Session = {
  "agent"?: {
    "id": string;
    "type"?: string;
  } & AdditionalProperties;
  "cwd"?: string;
  "id": string;
  "model"?: string;
  "workspaceRoots"?: Array<string>;
} & AdditionalProperties;

/** Source: schema/draft/session-end.schema.json# */
export type SessionEndEvent = {
  "extensions"?: Extensions;
  "id": string;
  "native"?: NativeEvent;
  "outcome"?: OpenString<"completed" | "cancelled" | "error" | "unknown">;
  "session": Session;
  "source": string;
  "time": string;
  "type": "session.end";
} & AdditionalProperties;

/** Source: schema/draft/session-start.schema.json# */
export type SessionStartEvent = {
  "extensions"?: Extensions;
  "id": string;
  "native"?: NativeEvent;
  "session": Session;
  "source": string;
  "time": string;
  "type": "session.start";
} & AdditionalProperties;

/** Source: schema/draft/registration.schema.json#/$defs/stdioTransport */
export type StdioTransport = {
  "args"?: Array<string>;
  "command": string;
  "cwd"?: string;
  "lifecycle": OpenString<"persistent" | "per_event">;
  "type": "stdio";
} & AdditionalProperties;

/** Source: schema/draft/tool-after.schema.json# */
export type ToolAfterEvent = {
  "extensions"?: Extensions;
  "id": string;
  "native"?: NativeEvent;
  "session": Session;
  "source": string;
  "time": string;
  "tool": {
    "callId": string;
    "input": {
    } & AdditionalProperties;
    "kind": OpenString<"shell" | "file_read" | "file_write" | "file_edit" | "search" | "fetch" | "task" | "mcp" | "other">;
    "mcp"?: {
    } & AdditionalProperties;
    "name": string;
    "output"?: JsonValue;
  } & AdditionalProperties;
  "type": "tool.after";
} & AdditionalProperties;

/** Source: schema/draft/tool-before.schema.json# */
export type ToolBeforeEvent = {
  "extensions"?: Extensions;
  "id": string;
  "native"?: NativeEvent;
  "session": Session;
  "source": string;
  "time": string;
  "tool": {
    "callId": string;
    "input": {
    } & AdditionalProperties;
    "kind": OpenString<"shell" | "file_read" | "file_write" | "file_edit" | "search" | "fetch" | "task" | "mcp" | "other">;
    "mcp"?: {
    } & AdditionalProperties;
    "name": string;
  } & AdditionalProperties;
  "type": "tool.before";
} & AdditionalProperties;

/** Source: schema/draft/tool-error.schema.json# */
export type ToolErrorEvent = {
  "extensions"?: Extensions;
  "id": string;
  "native"?: NativeEvent;
  "session": Session;
  "source": string;
  "time": string;
  "tool": {
    "callId": string;
    "error": {
      "category"?: JsonValue;
      "code"?: JsonValue;
      "message": JsonValue;
    } & AdditionalProperties;
    "input": {
    } & AdditionalProperties;
    "kind": OpenString<"shell" | "file_read" | "file_write" | "file_edit" | "search" | "fetch" | "task" | "mcp" | "other">;
    "mcp"?: {
    } & AdditionalProperties;
    "name": string;
  } & AdditionalProperties;
  "type": "tool.error";
} & AdditionalProperties;

/** Source: schema/draft/schema.json# */
export type WireMessage = InterceptRequest | InterceptNoEffectResponse | InterceptDenyResponse | JsonRpcErrorResponse | ObserveNotification;

const SCHEMAS: Record<string, SchemaNode> = {
  "Authentication": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "bearerToken"
      ],
      [
        "token"
      ],
      [
        "value"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "tokenEnv"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "bearer"
        },
        "wire_name": "type"
      }
    ]
  },
  "Backend": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Authentication"
        },
        "wire_name": "authentication"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "ReverseDnsName"
        },
        "wire_name": "id"
      },
      {
        "required": true,
        "shape": {
          "items": {
            "discriminator": "mode",
            "kind": "union",
            "mode": "oneOf",
            "variants": [
              {
                "kind": "ref",
                "name": "InterceptSubscription"
              },
              {
                "kind": "ref",
                "name": "ObserveSubscription"
              }
            ]
          },
          "kind": "array"
        },
        "wire_name": "subscriptions"
      },
      {
        "required": true,
        "shape": {
          "discriminator": "type",
          "kind": "union",
          "mode": "oneOf",
          "variants": [
            {
              "kind": "ref",
              "name": "StdioTransport"
            },
            {
              "kind": "ref",
              "name": "HttpTransport"
            }
          ]
        },
        "wire_name": "transport"
      }
    ]
  },
  "Capabilities": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "items": {
            "kind": "union",
            "mode": "anyOf",
            "variants": [
              {
                "kind": "literal",
                "value": "deny"
              },
              {
                "kind": "string"
              }
            ]
          },
          "kind": "array"
        },
        "wire_name": "effects"
      }
    ]
  },
  "DenyEffect": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "string"
        },
        "wire_name": "code"
      },
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Extensions"
        },
        "wire_name": "extensions"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "reason"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "deny"
        },
        "wire_name": "type"
      }
    ]
  },
  "Extensions": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": []
  },
  "HttpTransport": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "http"
        },
        "wire_name": "type"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "url"
      }
    ]
  },
  "InterceptDenyResponse": {
    "kind": "intersection",
    "variants": [
      {
        "kind": "ref",
        "name": "JsonRpcSuccessResponse"
      },
      {
        "additional": {
          "kind": "allowed"
        },
        "forbidden_property_sets": [],
        "kind": "object",
        "properties": [
          {
            "required": false,
            "shape": {
              "additional": {
                "kind": "allowed"
              },
              "forbidden_property_sets": [],
              "kind": "object",
              "properties": [
                {
                  "required": true,
                  "shape": {
                    "items": {
                      "kind": "ref",
                      "name": "DenyEffect"
                    },
                    "kind": "array"
                  },
                  "wire_name": "effects"
                },
                {
                  "required": false,
                  "shape": {
                    "kind": "ref",
                    "name": "Extensions"
                  },
                  "wire_name": "extensions"
                },
                {
                  "required": true,
                  "shape": {
                    "kind": "ref",
                    "name": "ProtocolVersion"
                  },
                  "wire_name": "protocolVersion"
                }
              ]
            },
            "wire_name": "result"
          }
        ]
      }
    ]
  },
  "InterceptNoEffectResponse": {
    "kind": "intersection",
    "variants": [
      {
        "kind": "ref",
        "name": "JsonRpcSuccessResponse"
      },
      {
        "additional": {
          "kind": "allowed"
        },
        "forbidden_property_sets": [],
        "kind": "object",
        "properties": [
          {
            "required": false,
            "shape": {
              "additional": {
                "kind": "allowed"
              },
              "forbidden_property_sets": [],
              "kind": "object",
              "properties": [
                {
                  "required": true,
                  "shape": {
                    "items": {
                      "kind": "any"
                    },
                    "kind": "array"
                  },
                  "wire_name": "effects"
                },
                {
                  "required": false,
                  "shape": {
                    "kind": "ref",
                    "name": "Extensions"
                  },
                  "wire_name": "extensions"
                },
                {
                  "required": true,
                  "shape": {
                    "kind": "ref",
                    "name": "ProtocolVersion"
                  },
                  "wire_name": "protocolVersion"
                }
              ]
            },
            "wire_name": "result"
          }
        ]
      }
    ]
  },
  "InterceptRequest": {
    "kind": "intersection",
    "variants": [
      {
        "kind": "ref",
        "name": "JsonRpcRequest"
      },
      {
        "additional": {
          "kind": "allowed"
        },
        "forbidden_property_sets": [],
        "kind": "object",
        "properties": [
          {
            "required": false,
            "shape": {
              "kind": "literal",
              "value": "hooks/intercept"
            },
            "wire_name": "method"
          },
          {
            "required": false,
            "shape": {
              "additional": {
                "kind": "allowed"
              },
              "forbidden_property_sets": [],
              "kind": "object",
              "properties": [
                {
                  "required": true,
                  "shape": {
                    "kind": "intersection",
                    "variants": [
                      {
                        "kind": "ref",
                        "name": "Capabilities"
                      },
                      {
                        "additional": {
                          "kind": "allowed"
                        },
                        "forbidden_property_sets": [],
                        "kind": "object",
                        "properties": [
                          {
                            "required": false,
                            "shape": {
                              "kind": "any"
                            },
                            "wire_name": "effects"
                          }
                        ]
                      }
                    ]
                  },
                  "wire_name": "capabilities"
                },
                {
                  "required": true,
                  "shape": {
                    "kind": "ref",
                    "name": "ToolBeforeEvent"
                  },
                  "wire_name": "event"
                },
                {
                  "required": false,
                  "shape": {
                    "kind": "ref",
                    "name": "Extensions"
                  },
                  "wire_name": "extensions"
                },
                {
                  "required": true,
                  "shape": {
                    "kind": "ref",
                    "name": "ProtocolVersion"
                  },
                  "wire_name": "protocolVersion"
                }
              ]
            },
            "wire_name": "params"
          }
        ]
      }
    ]
  },
  "InterceptSubscription": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "items": {
            "kind": "literal",
            "value": "tool.before"
          },
          "kind": "array"
        },
        "wire_name": "events"
      },
      {
        "required": true,
        "shape": {
          "kind": "enum",
          "open_strings": true,
          "values": [
            "fail-open",
            "fail-closed"
          ]
        },
        "wire_name": "failurePolicy"
      },
      {
        "required": false,
        "shape": {
          "kind": "boolean"
        },
        "wire_name": "includeNative"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "intercept"
        },
        "wire_name": "mode"
      },
      {
        "required": true,
        "shape": {
          "kind": "integer"
        },
        "wire_name": "timeoutMs"
      }
    ]
  },
  "JsonRpcErrorResponse": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "result"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [],
          "kind": "object",
          "properties": [
            {
              "required": true,
              "shape": {
                "kind": "integer"
              },
              "wire_name": "code"
            },
            {
              "required": false,
              "shape": {
                "kind": "any"
              },
              "wire_name": "data"
            },
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "message"
            }
          ]
        },
        "wire_name": "error"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "JsonRpcResponseId"
        },
        "wire_name": "id"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "2.0"
        },
        "wire_name": "jsonrpc"
      }
    ]
  },
  "JsonRpcId": {
    "kind": "union",
    "mode": "anyOf",
    "variants": [
      {
        "kind": "string"
      },
      {
        "kind": "integer"
      }
    ]
  },
  "JsonRpcMessage": {
    "kind": "union",
    "mode": "oneOf",
    "variants": [
      {
        "kind": "ref",
        "name": "JsonRpcRequest"
      },
      {
        "kind": "ref",
        "name": "JsonRpcNotification"
      },
      {
        "kind": "ref",
        "name": "JsonRpcSuccessResponse"
      },
      {
        "kind": "ref",
        "name": "JsonRpcErrorResponse"
      }
    ]
  },
  "JsonRpcNotification": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "id"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "2.0"
        },
        "wire_name": "jsonrpc"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "method"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [],
          "kind": "object",
          "properties": []
        },
        "wire_name": "params"
      }
    ]
  },
  "JsonRpcRequest": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "JsonRpcId"
        },
        "wire_name": "id"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "2.0"
        },
        "wire_name": "jsonrpc"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "method"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [],
          "kind": "object",
          "properties": []
        },
        "wire_name": "params"
      }
    ]
  },
  "JsonRpcResponseId": {
    "kind": "union",
    "mode": "anyOf",
    "variants": [
      {
        "kind": "ref",
        "name": "JsonRpcId"
      },
      {
        "kind": "null"
      }
    ]
  },
  "JsonRpcSuccessResponse": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "error"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "JsonRpcResponseId"
        },
        "wire_name": "id"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "2.0"
        },
        "wire_name": "jsonrpc"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [],
          "kind": "object",
          "properties": []
        },
        "wire_name": "result"
      }
    ]
  },
  "NativeEvent": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "eventName"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [],
          "kind": "object",
          "properties": []
        },
        "wire_name": "payload"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "provider"
      }
    ]
  },
  "ObserveNotification": {
    "kind": "intersection",
    "variants": [
      {
        "kind": "ref",
        "name": "JsonRpcNotification"
      },
      {
        "additional": {
          "kind": "allowed"
        },
        "forbidden_property_sets": [],
        "kind": "object",
        "properties": [
          {
            "required": false,
            "shape": {
              "kind": "literal",
              "value": "hooks/observe"
            },
            "wire_name": "method"
          },
          {
            "required": false,
            "shape": {
              "additional": {
                "kind": "allowed"
              },
              "forbidden_property_sets": [],
              "kind": "object",
              "properties": [
                {
                  "required": true,
                  "shape": {
                    "discriminator": "type",
                    "kind": "union",
                    "mode": "oneOf",
                    "variants": [
                      {
                        "kind": "ref",
                        "name": "ToolBeforeEvent"
                      },
                      {
                        "kind": "ref",
                        "name": "ToolAfterEvent"
                      },
                      {
                        "kind": "ref",
                        "name": "ToolErrorEvent"
                      },
                      {
                        "kind": "ref",
                        "name": "SessionStartEvent"
                      },
                      {
                        "kind": "ref",
                        "name": "SessionEndEvent"
                      }
                    ]
                  },
                  "wire_name": "event"
                },
                {
                  "required": true,
                  "shape": {
                    "kind": "ref",
                    "name": "ProtocolVersion"
                  },
                  "wire_name": "protocolVersion"
                }
              ]
            },
            "wire_name": "params"
          }
        ]
      }
    ]
  },
  "ObserveSubscription": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "failurePolicy"
      ],
      [
        "timeoutMs"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "items": {
            "kind": "enum",
            "open_strings": true,
            "values": [
              "tool.before",
              "tool.after",
              "tool.error",
              "session.start",
              "session.end"
            ]
          },
          "kind": "array"
        },
        "wire_name": "events"
      },
      {
        "required": false,
        "shape": {
          "kind": "boolean"
        },
        "wire_name": "includeNative"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "observe"
        },
        "wire_name": "mode"
      }
    ]
  },
  "ProtocolVersion": {
    "kind": "literal",
    "value": "draft"
  },
  "Registration": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": true,
        "shape": {
          "items": {
            "kind": "ref",
            "name": "Backend"
          },
          "kind": "array"
        },
        "wire_name": "hooks"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "ProtocolVersion"
        },
        "wire_name": "protocolVersion"
      }
    ]
  },
  "ReverseDnsName": {
    "kind": "string"
  },
  "Session": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [],
          "kind": "object",
          "properties": [
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "id"
            },
            {
              "required": false,
              "shape": {
                "kind": "string"
              },
              "wire_name": "type"
            }
          ]
        },
        "wire_name": "agent"
      },
      {
        "required": false,
        "shape": {
          "kind": "string"
        },
        "wire_name": "cwd"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "id"
      },
      {
        "required": false,
        "shape": {
          "kind": "string"
        },
        "wire_name": "model"
      },
      {
        "required": false,
        "shape": {
          "items": {
            "kind": "string"
          },
          "kind": "array"
        },
        "wire_name": "workspaceRoots"
      }
    ]
  },
  "SessionEndEvent": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "tool"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Extensions"
        },
        "wire_name": "extensions"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "id"
      },
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "NativeEvent"
        },
        "wire_name": "native"
      },
      {
        "required": false,
        "shape": {
          "kind": "enum",
          "open_strings": true,
          "values": [
            "completed",
            "cancelled",
            "error",
            "unknown"
          ]
        },
        "wire_name": "outcome"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "Session"
        },
        "wire_name": "session"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "source"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "time"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "session.end"
        },
        "wire_name": "type"
      }
    ]
  },
  "SessionStartEvent": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [
      [
        "outcome"
      ],
      [
        "tool"
      ]
    ],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Extensions"
        },
        "wire_name": "extensions"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "id"
      },
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "NativeEvent"
        },
        "wire_name": "native"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "Session"
        },
        "wire_name": "session"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "source"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "time"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "session.start"
        },
        "wire_name": "type"
      }
    ]
  },
  "StdioTransport": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "items": {
            "kind": "string"
          },
          "kind": "array"
        },
        "wire_name": "args"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "command"
      },
      {
        "required": false,
        "shape": {
          "kind": "string"
        },
        "wire_name": "cwd"
      },
      {
        "required": true,
        "shape": {
          "kind": "enum",
          "open_strings": true,
          "values": [
            "persistent",
            "per_event"
          ]
        },
        "wire_name": "lifecycle"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "stdio"
        },
        "wire_name": "type"
      }
    ]
  },
  "ToolAfterEvent": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Extensions"
        },
        "wire_name": "extensions"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "id"
      },
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "NativeEvent"
        },
        "wire_name": "native"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "Session"
        },
        "wire_name": "session"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "source"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "time"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [
            [
              "error"
            ]
          ],
          "kind": "object",
          "properties": [
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "callId"
            },
            {
              "required": true,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": []
              },
              "wire_name": "input"
            },
            {
              "required": true,
              "shape": {
                "kind": "enum",
                "open_strings": true,
                "values": [
                  "shell",
                  "file_read",
                  "file_write",
                  "file_edit",
                  "search",
                  "fetch",
                  "task",
                  "mcp",
                  "other"
                ]
              },
              "wire_name": "kind"
            },
            {
              "required": false,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": []
              },
              "wire_name": "mcp"
            },
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "name"
            },
            {
              "required": false,
              "shape": {
                "kind": "any"
              },
              "wire_name": "output"
            }
          ]
        },
        "wire_name": "tool"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "tool.after"
        },
        "wire_name": "type"
      }
    ]
  },
  "ToolBeforeEvent": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Extensions"
        },
        "wire_name": "extensions"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "id"
      },
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "NativeEvent"
        },
        "wire_name": "native"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "Session"
        },
        "wire_name": "session"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "source"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "time"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [
            [
              "error"
            ],
            [
              "output"
            ]
          ],
          "kind": "object",
          "properties": [
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "callId"
            },
            {
              "required": true,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": []
              },
              "wire_name": "input"
            },
            {
              "required": true,
              "shape": {
                "kind": "enum",
                "open_strings": true,
                "values": [
                  "shell",
                  "file_read",
                  "file_write",
                  "file_edit",
                  "search",
                  "fetch",
                  "task",
                  "mcp",
                  "other"
                ]
              },
              "wire_name": "kind"
            },
            {
              "required": false,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": []
              },
              "wire_name": "mcp"
            },
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "name"
            }
          ]
        },
        "wire_name": "tool"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "tool.before"
        },
        "wire_name": "type"
      }
    ]
  },
  "ToolErrorEvent": {
    "additional": {
      "kind": "allowed"
    },
    "forbidden_property_sets": [],
    "kind": "object",
    "properties": [
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "Extensions"
        },
        "wire_name": "extensions"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "id"
      },
      {
        "required": false,
        "shape": {
          "kind": "ref",
          "name": "NativeEvent"
        },
        "wire_name": "native"
      },
      {
        "required": true,
        "shape": {
          "kind": "ref",
          "name": "Session"
        },
        "wire_name": "session"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "source"
      },
      {
        "required": true,
        "shape": {
          "kind": "string"
        },
        "wire_name": "time"
      },
      {
        "required": true,
        "shape": {
          "additional": {
            "kind": "allowed"
          },
          "forbidden_property_sets": [
            [
              "output"
            ]
          ],
          "kind": "object",
          "properties": [
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "callId"
            },
            {
              "required": true,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": [
                  {
                    "required": false,
                    "shape": {
                      "kind": "any"
                    },
                    "wire_name": "category"
                  },
                  {
                    "required": false,
                    "shape": {
                      "kind": "any"
                    },
                    "wire_name": "code"
                  },
                  {
                    "required": true,
                    "shape": {
                      "kind": "any"
                    },
                    "wire_name": "message"
                  }
                ]
              },
              "wire_name": "error"
            },
            {
              "required": true,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": []
              },
              "wire_name": "input"
            },
            {
              "required": true,
              "shape": {
                "kind": "enum",
                "open_strings": true,
                "values": [
                  "shell",
                  "file_read",
                  "file_write",
                  "file_edit",
                  "search",
                  "fetch",
                  "task",
                  "mcp",
                  "other"
                ]
              },
              "wire_name": "kind"
            },
            {
              "required": false,
              "shape": {
                "additional": {
                  "kind": "allowed"
                },
                "forbidden_property_sets": [],
                "kind": "object",
                "properties": []
              },
              "wire_name": "mcp"
            },
            {
              "required": true,
              "shape": {
                "kind": "string"
              },
              "wire_name": "name"
            }
          ]
        },
        "wire_name": "tool"
      },
      {
        "required": true,
        "shape": {
          "kind": "literal",
          "value": "tool.error"
        },
        "wire_name": "type"
      }
    ]
  },
  "WireMessage": {
    "kind": "union",
    "mode": "oneOf",
    "variants": [
      {
        "kind": "ref",
        "name": "InterceptRequest"
      },
      {
        "kind": "ref",
        "name": "InterceptNoEffectResponse"
      },
      {
        "kind": "ref",
        "name": "InterceptDenyResponse"
      },
      {
        "kind": "ref",
        "name": "JsonRpcErrorResponse"
      },
      {
        "kind": "ref",
        "name": "ObserveNotification"
      }
    ]
  }
} as unknown as Record<string, SchemaNode>;
function parseRoot(name: string, input: string | unknown): ParseResult<unknown> {
  let raw: JsonValue;
  try {
    raw = toSafeJson(typeof input === "string" ? JSON.parse(input) : input);
  } catch (error) {
    return { ok: false, diagnostics: [{ path: "", code: "invalid_json", severity: "error", message: error instanceof Error ? error.message : "Invalid JSON" }] };
  }
  const diagnostics: ParseDiagnostic[] = [];
  checkNode(SCHEMAS[name]!, raw, "", diagnostics);
  if (diagnostics.some((diagnostic) => diagnostic.severity === "error")) return { ok: false, raw, diagnostics };
  return { ok: true, value: raw, raw, diagnostics };
}

function checkNode(schema: SchemaNode, value: JsonValue, path: string, diagnostics: ParseDiagnostic[]): void {
  switch (schema.kind) {
    case "any": return;
    case "never": return error(diagnostics, path, "invalid_type", "Value is forbidden");
    case "null": if (value !== null) error(diagnostics, path, "invalid_type", "Expected null"); return;
    case "boolean": if (typeof value !== "boolean") error(diagnostics, path, "invalid_type", "Expected boolean"); return;
    case "integer": if (typeof value !== "number" || !Number.isSafeInteger(value)) error(diagnostics, path, "invalid_type", "Expected safely representable integer"); return;
    case "number": if (typeof value !== "number" || !Number.isFinite(value)) error(diagnostics, path, "invalid_type", "Expected finite number"); return;
    case "string": if (typeof value !== "string") error(diagnostics, path, "invalid_type", "Expected string"); return;
    case "literal": if (!sameJson(value, schema.value)) error(diagnostics, path, "literal_mismatch", `Expected ${JSON.stringify(schema.value)}`); return;
    case "enum": {
      if (schema.values.some((candidate) => sameJson(candidate, value))) return;
      if (schema.open_strings && typeof value === "string") {
        diagnostics.push({ path, code: "unknown_enum", severity: "warning", message: `Unknown enum value ${JSON.stringify(value)} was preserved` });
      } else error(diagnostics, path, "invalid_type", "Value does not match the enum's scalar type");
      return;
    }
    case "array":
      if (!Array.isArray(value)) return error(diagnostics, path, "invalid_type", "Expected array");
      value.forEach((item, index) => checkNode(schema.items, item, `${path}/${index}`, diagnostics));
      return;
    case "object":
      if (!isObject(value)) return error(diagnostics, path, "invalid_type", "Expected object");
      for (const forbiddenSet of schema.forbidden_property_sets) {
        if (forbiddenSet.every((key) => Object.prototype.hasOwnProperty.call(value, key))) {
          error(diagnostics, path, "invalid_type", `Forbidden property combination: ${forbiddenSet.join(", ")}`);
        }
      }
      for (const property of schema.properties) {
        if (!Object.prototype.hasOwnProperty.call(value, property.wire_name)) {
          if (property.required) error(diagnostics, joinPath(path, property.wire_name), "missing_required", "Required property is absent");
        } else checkNode(property.shape, value[property.wire_name]!, joinPath(path, property.wire_name), diagnostics);
      }
      return;
    case "intersection": schema.variants.forEach((variant) => checkNode(variant, value, path, diagnostics)); return;
    case "ref": checkNode(SCHEMAS[schema.name]!, value, path, diagnostics); return;
    case "union": checkUnion(schema, value, path, diagnostics); return;
  }
}

function checkUnion(schema: Extract<SchemaNode, { kind: "union" }>, value: JsonValue, path: string, diagnostics: ParseDiagnostic[]): void {
  if (schema.discriminator) {
    if (!isObject(value) || typeof value[schema.discriminator] !== "string") return error(diagnostics, joinPath(path, schema.discriminator), "invalid_type", "Expected string discriminator");
    const actual = value[schema.discriminator] as string;
    const branch = schema.variants.find((variant) => discriminatorValue(variant, schema.discriminator as string) === actual);
    if (!branch) {
      diagnostics.push({ path, code: "unknown_variant", severity: "warning", message: `Unknown ${schema.discriminator} variant ${JSON.stringify(actual)} was preserved` });
      return;
    }
    const branchDiagnostics: ParseDiagnostic[] = [];
    checkNode(branch, value, path, branchDiagnostics);
    if (branchDiagnostics.some((item) => item.severity === "error")) {
      diagnostics.push(...branchDiagnostics, { path, code: "invalid_known_variant", severity: "error", message: `Known ${schema.discriminator} variant is malformed` });
    } else diagnostics.push(...branchDiagnostics);
    return;
  }
  const attempts = schema.variants.map((variant) => { const result: ParseDiagnostic[] = []; checkNode(variant, value, path, result); return result; });
  const matches = attempts.filter((attempt) => !attempt.some((item) => item.severity === "error"));
  if (matches.length === 0) error(diagnostics, path, "no_union_match", "Value matches no union branch");
  else if (schema.mode === "oneOf" && matches.length > 1) error(diagnostics, path, "ambiguous_union", "Value matches more than one union branch");
  else diagnostics.push(...matches[0]!);
}

function discriminatorValue(schema: SchemaNode, property: string): string | undefined {
  if (schema.kind === "ref") return discriminatorValue(SCHEMAS[schema.name]!, property);
  if (schema.kind === "intersection") {
    for (const variant of schema.variants) { const value = discriminatorValue(variant, property); if (value !== undefined) return value; }
  }
  if (schema.kind === "object") {
    const field = schema.properties.find((candidate) => candidate.wire_name === property);
    if (field?.shape.kind === "literal" && typeof field.shape.value === "string") return field.shape.value;
  }
  return undefined;
}

function toSafeJson(value: unknown): JsonValue {
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (Array.isArray(value)) return value.map(toSafeJson);
  if (typeof value === "object") {
    const result = Object.create(null) as Record<string, JsonValue>;
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      Object.defineProperty(result, key, { value: toSafeJson(child), enumerable: true, configurable: true, writable: true });
    }
    return result;
  }
  throw new TypeError("Input is not a JSON value");
}

function encodeJson(value: JsonValue): string { return JSON.stringify(value); }
function isObject(value: JsonValue): value is Record<string, JsonValue> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function sameJson(left: JsonValue, right: JsonValue): boolean { return JSON.stringify(left) === JSON.stringify(right); }
function joinPath(path: string, key: string): string { return `${path}/${key.replace(/~/g, "~0").replace(/\//g, "~1")}`; }
function error(diagnostics: ParseDiagnostic[], path: string, code: ParseDiagnostic["code"], message: string): void { diagnostics.push({ path, code, severity: "error", message }); }
export function parseCapabilities(input: string | unknown): ParseResult<Capabilities> { return parseRoot("Capabilities", input) as ParseResult<Capabilities>; }
export function encodeCapabilities(value: Capabilities): string { return encodeJson(value as JsonValue); }
export const capabilitiesSchemaRevision = SCHEMA_REVISION;

export function parseDenyEffect(input: string | unknown): ParseResult<DenyEffect> { return parseRoot("DenyEffect", input) as ParseResult<DenyEffect>; }
export function encodeDenyEffect(value: DenyEffect): string { return encodeJson(value as JsonValue); }
export const denyEffectSchemaRevision = SCHEMA_REVISION;

export function parseExtensions(input: string | unknown): ParseResult<Extensions> { return parseRoot("Extensions", input) as ParseResult<Extensions>; }
export function encodeExtensions(value: Extensions): string { return encodeJson(value as JsonValue); }
export const extensionsSchemaRevision = SCHEMA_REVISION;

export function parseInterceptDenyResponse(input: string | unknown): ParseResult<InterceptDenyResponse> { return parseRoot("InterceptDenyResponse", input) as ParseResult<InterceptDenyResponse>; }
export function encodeInterceptDenyResponse(value: InterceptDenyResponse): string { return encodeJson(value as JsonValue); }
export const interceptDenyResponseSchemaRevision = SCHEMA_REVISION;

export function parseInterceptNoEffectResponse(input: string | unknown): ParseResult<InterceptNoEffectResponse> { return parseRoot("InterceptNoEffectResponse", input) as ParseResult<InterceptNoEffectResponse>; }
export function encodeInterceptNoEffectResponse(value: InterceptNoEffectResponse): string { return encodeJson(value as JsonValue); }
export const interceptNoEffectResponseSchemaRevision = SCHEMA_REVISION;

export function parseInterceptRequest(input: string | unknown): ParseResult<InterceptRequest> { return parseRoot("InterceptRequest", input) as ParseResult<InterceptRequest>; }
export function encodeInterceptRequest(value: InterceptRequest): string { return encodeJson(value as JsonValue); }
export const interceptRequestSchemaRevision = SCHEMA_REVISION;

export function parseJsonRpcMessage(input: string | unknown): ParseResult<JsonRpcMessage> { return parseRoot("JsonRpcMessage", input) as ParseResult<JsonRpcMessage>; }
export function encodeJsonRpcMessage(value: JsonRpcMessage): string { return encodeJson(value as JsonValue); }
export const jsonRpcMessageSchemaRevision = SCHEMA_REVISION;

export function parseObserveNotification(input: string | unknown): ParseResult<ObserveNotification> { return parseRoot("ObserveNotification", input) as ParseResult<ObserveNotification>; }
export function encodeObserveNotification(value: ObserveNotification): string { return encodeJson(value as JsonValue); }
export const observeNotificationSchemaRevision = SCHEMA_REVISION;

export function parseRegistration(input: string | unknown): ParseResult<Registration> { return parseRoot("Registration", input) as ParseResult<Registration>; }
export function encodeRegistration(value: Registration): string { return encodeJson(value as JsonValue); }
export const registrationSchemaRevision = SCHEMA_REVISION;

export function parseSessionEndEvent(input: string | unknown): ParseResult<SessionEndEvent> { return parseRoot("SessionEndEvent", input) as ParseResult<SessionEndEvent>; }
export function encodeSessionEndEvent(value: SessionEndEvent): string { return encodeJson(value as JsonValue); }
export const sessionEndEventSchemaRevision = SCHEMA_REVISION;

export function parseSessionStartEvent(input: string | unknown): ParseResult<SessionStartEvent> { return parseRoot("SessionStartEvent", input) as ParseResult<SessionStartEvent>; }
export function encodeSessionStartEvent(value: SessionStartEvent): string { return encodeJson(value as JsonValue); }
export const sessionStartEventSchemaRevision = SCHEMA_REVISION;

export function parseToolAfterEvent(input: string | unknown): ParseResult<ToolAfterEvent> { return parseRoot("ToolAfterEvent", input) as ParseResult<ToolAfterEvent>; }
export function encodeToolAfterEvent(value: ToolAfterEvent): string { return encodeJson(value as JsonValue); }
export const toolAfterEventSchemaRevision = SCHEMA_REVISION;

export function parseToolBeforeEvent(input: string | unknown): ParseResult<ToolBeforeEvent> { return parseRoot("ToolBeforeEvent", input) as ParseResult<ToolBeforeEvent>; }
export function encodeToolBeforeEvent(value: ToolBeforeEvent): string { return encodeJson(value as JsonValue); }
export const toolBeforeEventSchemaRevision = SCHEMA_REVISION;

export function parseToolErrorEvent(input: string | unknown): ParseResult<ToolErrorEvent> { return parseRoot("ToolErrorEvent", input) as ParseResult<ToolErrorEvent>; }
export function encodeToolErrorEvent(value: ToolErrorEvent): string { return encodeJson(value as JsonValue); }
export const toolErrorEventSchemaRevision = SCHEMA_REVISION;

export function parseWireMessage(input: string | unknown): ParseResult<WireMessage> { return parseRoot("WireMessage", input) as ParseResult<WireMessage>; }
export function encodeWireMessage(value: WireMessage): string { return encodeJson(value as JsonValue); }
export const wireMessageSchemaRevision = SCHEMA_REVISION;

